apiVersion: etl/v1
kind: Deployment
metadata:
  name: etl
spec:
  containers:
  - name: gcp-data-lake-analytics-etl
    image: gcp-data-lake-analytics/etl:1.0
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 5000
