apiVersion: etl/v1
kind: Deployment
metadata:
  name: etl
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: gcp-data-lake-analytics-etl
        image: gcp-data-lake-analytics/etl:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
