FROM python:3.7-slim-buster
LABEL maintainer="israel.mendez232@gmail.com"
LABEL version="1.0"
LABEL description="Script to get and upload files from the Bitfinex API."

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

VOLUME /script/
EXPOSE 8888

CMD ["./scripts/etl.py", "-flag"]
