FROM python:3.8-slim-buster
LABEL maintainer="israel.mendez232@gmail.com"
LABEL version="1.0"
LABEL description="Script to get and upload files from the Bitfinex API."

COPY requirements.txt requirements.txt
COPY .env .env

RUN pip3 install -r requirements.txt

VOLUME /scripts/
EXPOSE 8888

CMD [ "python3", "./scripts/etl.py" ]
